# 1. donde recogemos los datos de mqtt
[[inputs.mqtt_consumer]]
  servers = ["tcp://broker_mqtt:1883"]
  topics = [ "ventilador/estado" ]
  data_format = "json"
  json_string_fields = ["estado"]

# 2. donde llevamos los datos
[[outputs.influxdb]]
  urls = ["http://base_datos:8086"]
  database = "sensores"
